{% set name = "cfgrib" %}
{% set version = "0.9.7.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b79433cde96961ac809842148bc7020fa8867c3d8bc36eedbcf0f69543632fa1

build:
  noarch: python
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - attrs
    - cffi
    - click
    - eccodes >=2.12.0
    - numpy
    - xarray >=0.12.0

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - StephanSiemen
